
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
spring:
  application:
    name: ai-spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: file://${user.home}/config-repo
  profiles:
    active: dev
server:
  port: 9003