spring:
  application:
    name: ai-spring-cloud-zuul

server:
  port: 9002

zuul:
  ignoredServices: '*'
  routes:
    sso:
      path: /sso/*
      url: forward:/greeting
    myservices:
      path: /api/ms/**
      serviceId: ai-spring-cloud-myservice

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/